os: linux
language: python
branches:
  only:
  - master
  - /.*/
script: 
  - echo "Rebuild binder image"
#after_success:
  #- bash binder/trigger_binder.sh https://gke.mybinder.org/build/gh/johntfoster-pge-utexas/numerical-methods-book/"${TRAVIS_BRANCH}"
  #- bash binder/trigger_binder.sh https://ovh.mybinder.org/build/gh/johntfoster-pge-utexas/numerical-methods-book/"${TRAVIS_BRANCH}"
